version: '3.8'

services:
  tickora-hub:
    build: .
    container_name: tickora-monitoring
    restart: unless-stopped
    ports:
      - "8501:8501"
    pid: "host"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/log/postgresql:/var/log/postgresql:ro
      - /var/log/redis:/var/log/redis:ro
      - /home/finytive1/Tickora/tms-monorepo/logs:/home/finytive1/Tickora/tms-monorepo/logs:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M